name: Build with Latest Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        backend: ["windows-mingw", "windows-msvc"]
        os: ["windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Fetch Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download --repo The-Goo-Goo-Gang/nogo-backend -n ${{ matrix.backend }}-artifact -D .\server
          rm .\server\nogo-test*

      - name: Build
        run: |
          yarn install
          yarn run electron:build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-windows-backend-${{ matrix.backend }}
          path: |
            dist_electron\NoGo*.exe
            dist_electron\NoGo*.7z
